config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'static_pages#home'

  
  resources :comment

  resources :users, except: [:new], path: 'usuarios'

  get '/cadastro', to: 'users#new'

  get '/todos', to: 'users#feed'

  get '/perfil', to: 'users#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/comments', to: 'comment#index'
  post '/comments', to: 'comment#index'
  get '/comment/new', to: 'comment#new'

  get '/new', to: 'users#index'

  get '/amigos', to: 'friendships#index'

  resources :friendships


  patch 'like/:post_id', to: "posts#like", as: :like
  patch 'like/:post_id', to: "posts#dislike", as: :dislike


  

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

 
end

app/controllers/comment_controller.rb
	class CommentController < ApplicationController


	def index
	end

	def new
		@comment = Comment.new
	
	end

	def create
		@comment = Comment.new(comment_params)

		respond_to do |format|
			if @comment.save
				flash[:notice] = "Seu comentário foi postado!"
				redirect_to post_path
			else
				redirect_to new_comment_path
			end
		end
				
	end

	def update
		respond_to do |format|
			if @comment.update(comment_params)
				flash[:notice] = "Comentário atualizado!"
				redirect_to post_path
				
			else
				render 'edit'
			end
		end

	end

	def destroy
		if current_user.id == @comment.user_id
			@comment.destroy #quando eu chamo o destroy nesse caso, eu preciso fazer algo para especificar que é o comentário em questão ou não precisa
		else
			flash[:notice] = "Você não tem autorização para isso!"
			redirect_to post_path
		end
	end


	private

	def set_comment
	@comment = Comment.find(params[:id])
	end

	def comment_params
	params.require(:comment).permit(:user_id, :post_id, :comment_box)

	end


end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comment/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
	<% if comment.errors.any? %>
	<div id="error_explanation">
		<h2><%=pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:%></h2>
		<ul>
			<% comment.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :comment_box %>
    <%= form.text_area :comment_box %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar para todos os posts', posts_path%>

app/views/comment/edit.html.erb
<h1>Edite seu comentário</h1>

<%= render 'form', comment: @comment %>


<%= link_to 'Voltar ao post', post_path %>

app/views/comment/index.html.erb
<br>
<%= link_to 'Voltar', posts_path %> | <%= link_to 'FEED', todos_path%>

app/views/comment/new.html.erb
<h1> Novo comentário </h1>

<%= render 'form', comment: @comment %>