config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'static_pages#home'

  
  resources :comment

  resources :users, except: [:new], path: 'usuarios'

  get '/cadastro', to: 'users#new'

  get '/todos', to: 'users#feed'

  get '/perfil', to: 'users#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/comments', to: 'comment#index'
  post '/comments', to: 'comment#index'
  get '/comment/new', to: 'comment#new'

  get '/new', to: 'users#index'

  get '/amigos', to: 'friendships#index'

  resources :friendships


  patch 'like/:post_id', to: "posts#like", as: :like
  patch 'like/:post_id', to: "posts#dislike", as: :dislike


  

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6}
    validates :email, presence: true, uniqueness: true

    has_many :posts
    has_many :comments  

    has_many :friendships
    has_many :friends, :through => :friendships

    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user

    has_many :likes

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :nao_logado, except: [:new, :create]  #impede pessoas que não estão logadas de acessar páginas que só pessoas logadas podem
    before_action :logado, only: [:new] #impede que pessoas logadas façam o login novamente

    def index
        @users = User.all
    end

    def feed
        @users = User.all
        @posts = Post.all
        @friendships = Friendship.all
        @user = current_user

    end


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def index
        @users = User.all
    
    end

    def destroy
		if current_user.id == user_id
            @user.destroy #quando eu chamo o destroy nesse caso, eu preciso fazer algo para especificar que é o comentário em questão ou não precisa
            redirect_to login_path
		else
			flash[:notice] = "Você não tem autorização para isso!"
			redirect_to todos_path
		end
	end

    def show
        @user = User.find(params[:id])
        Friendship.where(user_id: @current_user.id)
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

        def nao_logado
            if !logged_in?
                redirect_to root_path
            end
        end

        def logado
            if logged_in?
                redirect_to current_user
            end
        end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <div class="field">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>
    <div class="field">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password, "Senha" %>
        <%= form.password_field :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation, "Confirmar senha" %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
    <%= form.submit "Cadastrar"%>
    </div>

    <% end %>

    <%= link_to "Já possui conta? Faça o login", login_path %>

app/views/users/feed.html.erb
<p id="notice"><%= notice %></p>

<br>

<h1> FEED </h1>

<br>


<%= link_to 'Novo post', new_post_path %>

<br><br>


    
 <% @friendships.each do |friendship|  %>
    <h2><%=friendship.friend.name %></h2>
    <br>
    <%=friendship.friend.posts %>
    <br>
    <br>
    
    <%= link_to 'Ver post', @post %> | <%= link_to 'Ver perfil', friendship %>
    <br>
    <br>
  

<% end %>  

    

    <br><br>
    <%= link_to 'Todos os posts', posts_path %> | <%= link_to 'Quem está por aqui?', new_path %>
    
    <br><br>
    <br><br>
  

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>



    <h1>Conheça pessoas novas: </h1>

    <% @users.each do |user| %>
        <p><strong><%=user.name %></strong>
            <%= link_to "+ amigo", friendships_path(:friend_id => user), :method => :post %>
            <%= link_to 'Ver perfil', user %>
        </p>
    <% end %>   

    <br><br>
    <%= link_to 'Todos os posts', posts_path %>
    <br><br><br>
    <%= link_to 'Meu perfil', login_path %>

        


 

app/views/users/new.html.erb
<h1>Cadastre-se!</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

 <h1>Meu perfil</h1>


  <p><%= @user.name %></h2> <%= link_to "+ amigo", friendships_path(:friend_id => @user), :method => :post %></p>
  


<p><%= link_to "Amigos", amigos_path %></p>
<h2>Pessoas que você adicionou</h2>
<%if @friendships.present?%>
    <% @friendships.each do |friendship| %>
    <li>
      <%=friendship.friend.name %>
      (<%= link_to "desfazer amizade", friendship, :method => :delete %>)
          <%= link_to 'Ver perfil', friendship.friend%>
    
    </li>
    <% end %>
<%end%>


<br>
<table>
  <thead><h2>Posts</h2></thead>
  <tbody>
    <% @user.posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
      </tr>
    <% end %>
    <tr><td><%= link_to 'Novo post', new_post_path %></td></tr>
  </tbody>
</table>
  
  <br>
  
  <% if @current_user == @user %>
    <h2>Outras opções</h2>
    <%= link_to 'Exluir perfil', @user, method: :delete, data: { confirm: 'Você está prestes a excluir seu perfil, é isso que deseja?' } %>
  <% end %>