config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'static_pages#home'

  
  resources :comment

  resources :users, except: [:new], path: 'usuarios'

  get '/cadastro', to: 'users#new'

  get '/todos', to: 'users#feed'

  get '/perfil', to: 'users#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/comments', to: 'comment#index'
  post '/comments', to: 'comment#index'
  get '/comment/new', to: 'comment#new'

  get '/new', to: 'users#index'

  get '/amigos', to: 'friendships#index'

  resources :friendships


  patch 'like/:post_id', to: "posts#like", as: :like
  patch 'like/:post_id', to: "posts#dislike", as: :dislike


  

  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_many :likes
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @comments = Comment.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @posts = Post.all
    @friendships = Friendship.all
    @comments = Comment.where(post_id: @post.id)
    
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post apagado!' }
      format.json { head :no_content }
    end
  end


  def like
    @post = Post.find_by(id: params[:post_id])
    current_user.like.build(post_id: params[:post_id]).save

    respond_to do |format|
      format.html {redirect_to show_post_path}
      format.js
    end
  end


  def dislike
    @post = Post.find_by(id: params[:post_id])
    current_user.like.build(post_id: params[:post_id]).destroy

    respond_to do |format|
      format.html {redirect_to todos_path}
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id, "Usuário" %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title, "Título" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, "Post" %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<% if Like.where(post_id: @post.id).empty? %>
        <p id="like<%= @post.id %>"><%= link_to "Curtir", like_path(post_id: @post.id),
            method: :patch, remote: true, authenticity_token: true %> (<%= Like.where(post_id: @post.id).count %>)</p>
    <% else %>
        <p id="dislike<%= @post.id %>"><%= link_to "Descurtir", dislike_path(post_id: @post.id),
            method: :patch, remote: true, authenticity_token: true %> (<%= Like.where(post_id: @post.id).count %>)</p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>



<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Título</th>
      <th>Post</th>
      <th>Comentários</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= link_to post.title, post %></td>
        <td><%= post.content %></td>
        <td><%= post.comments%>
       
       
        <% if @current_user == post.user_id %>
          <td><%= link_to 'Deletar', post, method: :delete, data: { confirm: 'Você quer mesmo deletar esse post?' } %></td>
           <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <% end %>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo post', new_post_path %>
<br>
<br>
<br>
<br>
<%= link_to 'FEED', todos_path%>

app/views/posts/new.html.erb
<h1>Nova publicação</h1>

<%= render 'form', post: @post %>

<%= link_to 'Todos os posts', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>

   <%= @post.title %>
   <br>
   <%= @post.content %>
   <br>
  <strong>Autor:</strong>
    <%= @post.user.name %>
    <br>
    <%= render "like" %>
    <%= link_to 'Comentar', new_comment_path %>
    <br>
    <%= @post.comments%>
</p>
 
  <br>
  <% @comments.each do |comment| %>

    <p><%= comment.comment_box %></p>
    <p><%= comment.user_id.name %></p>
  <% end %>
  <br>
  
  <br>
  <% if @current_user == @post.user_id %>
    <%= link_to 'Edit', edit_post_path(@post) %>
  <% end %>
  <br>
  

  <%= link_to 'Posts', posts_path %> 










 